import { PTCFileType } from "./PTCFileType";

enum PTCPackageBits {
    SPU0 = 0,
    SPU1,
    SPU2,
    SPU3,
    SPU4,
    SPU5,
    SPU6,
    SPU7,
    BGU0U,
    BGU1U,
    BGU2U,
    BGU3U,
    BGUFU,
    COL0U,
    COL1U,
    COL2U,
    SCU0U,
    SCU1U,
    GRP0,
    GRP1,
    GRP2,
    GRP3,
    MEM,
    SPD0,
    SPD1,
    SPD2,
    SPD3,
    BGU0L,
    BGU1L,
    BGU2L,
    BGU3L,
    BGUFL,
    COL0L,
    COL1L,
    COL2L,
    SCU0L,
    SCU1L,
    SPS0U,
    SPS1U,
    BGD0U,
    BGD1U,
    SPS0L,
    SPS1L,
    BGD0L,
    BGD1L
}

const PTCPackageTypes = new Map<number, PTCFileType>([
    [0, PTCFileType.CHR],
    [1, PTCFileType.CHR],
    [2, PTCFileType.CHR],
    [3, PTCFileType.CHR],
    [4, PTCFileType.CHR],
    [5, PTCFileType.CHR],
    [6, PTCFileType.CHR],
    [7, PTCFileType.CHR],
    [8, PTCFileType.CHR],
    [9, PTCFileType.CHR],
    [10, PTCFileType.CHR],
    [11, PTCFileType.CHR],
    [12, PTCFileType.CHR],
    [13, PTCFileType.COL],
    [14, PTCFileType.COL],
    [15, PTCFileType.COL],
    [16, PTCFileType.SCR],
    [17, PTCFileType.SCR],
    [18, PTCFileType.GRP],
    [19, PTCFileType.GRP],
    [20, PTCFileType.GRP],
    [21, PTCFileType.GRP],
    [22, PTCFileType.MEM],
    [23, PTCFileType.CHR],
    [24, PTCFileType.CHR],
    [25, PTCFileType.CHR],
    [26, PTCFileType.CHR],
    [27, PTCFileType.CHR],
    [28, PTCFileType.CHR],
    [29, PTCFileType.CHR],
    [30, PTCFileType.CHR],
    [31, PTCFileType.CHR],
    [32, PTCFileType.COL],
    [33, PTCFileType.COL],
    [34, PTCFileType.COL],
    [35, PTCFileType.SCR],
    [36, PTCFileType.SCR],
    [37, PTCFileType.CHR],
    [38, PTCFileType.CHR],
    [39, PTCFileType.CHR],
    [40, PTCFileType.CHR],
    [41, PTCFileType.CHR],
    [42, PTCFileType.CHR],
    [43, PTCFileType.CHR],
    [44, PTCFileType.CHR]
]);


export { PTCPackageBits, PTCPackageTypes };
